/** Admin strings. The admin needs a to-do list, not a database (CLAUDE.md §1). */
export const admin = {
  title: "Admin",
  viewSite: "View site",
  signOut: "Sign out",
  menu: "Menu",
  closeMenu: "Close menu",
  nav: {
    today: "Today",
    board: "Applications",
    payments: "Payments",
    renewals: "Renewals",
    agents: "Agents",
    automations: "Automations",
    outbox: "Messages",
  },
  navGroups: { work: "Work", money: "Money", system: "System" },
  boardHeading: "Today",
  boardSummary: (count: number) =>
    count === 0 ? "Nothing needs you right now." : count === 1 ? "1 thing needs you. Start here." : `${count} things need you. Start at the top.`,
  boardIntro: "Work from the top. Anything that needs you is in the first list.",
  backToBoard: "Back to applications",
  liveNote: "Updates by itself as clients act.",

  buckets: {
    needsMe: "Needs me now",
    waiting: "Waiting on client",
    quotesOut: "Quotes and payment",
    done: "Covered",
  },
  search: {
    label: "Search applications",
    placeholder: "Name, reference or number plate",
    none: (query: string) => `Nothing matches “${query}”. Try a name, a reference like BC-4821, or a plate.`,
  },

  empty: {
    needsMe: {
      title: "Nothing needs you right now",
      body: "New applications, stalled clients and replies appear here the moment they happen.",
    },
    other: {
      title: "Nothing here yet",
      body: "Applications move here on their own as they progress.",
    },
  },

  // Why an application is on the board, in the broker's words.
  badges: {
    paid: "Paid",
    new_submission: "New",
    stalled: "Stalled",
    replied: "Replied",
    documents_uploaded: "To check",
    ready_to_quote: "Ready for quotes",
  },
  notes: {
    new_submission: (ago: string) => `Sent ${ago}`,
    stalled: (step: number, total: number, ago: string) => `Stopped at step ${step} of ${total} · ${ago}`,
    replied: (ago: string) => `Replied ${ago}`,
    documents_uploaded: (ago: string) => `Uploaded a document ${ago}`,
    ready_to_quote: "Documents checked · ready for quotes",
    paid: (amount: string, ago: string) => `Paid ${amount} ${ago} · issue the cover`,
    awaitingPayment: (amount: string, ago: string) => `Chose cover ${ago} · waiting for ${amount}`,
    agent: (name: string) => `Referred by ${name}`,
    renewal: "Renewal",
    inProgress: (step: number, total: number, ago: string) => `Filling in · step ${step} of ${total} · ${ago}`,
    waitingFor: (doc: string, ago: string) => `Waiting for ${doc} · asked ${ago}`,
    waitingGeneric: (ago: string) => `Waiting on client · ${ago}`,
    quotesSent: (ago: string) => `Quotes sent ${ago}`,
    covered: (date: string) => `Covered · ${date}`,
  },
  // Status in the broker's words (the client sees lib/copy/status labels).
  statusLabels: {
    received: "Received",
    documents_checked: "Documents checked",
    preparing_quotes: "Preparing quotes",
    needs_info: "Asked for more",
    quotes_ready: "Quotes sent",
    cover_chosen: "Awaiting payment",
    paid: "Paid — issue cover",
    covered: "Covered",
  },
  docStatus: {
    needed: "Not uploaded",
    uploaded: "To check",
    verified: "Verified",
    rejected: "Re-upload asked",
  },
  answerLabels: {
    product: "Insurance",
    name: "Name",
    phone: "Phone",
    coverType: "Type of cover",
    vehicleValueKes: "Value",
    usage: "Use",
    submitted: "Sent",
    started: "Started",
    email: "Email",
    category: "Vehicle use",
    seats: "Passenger seats",
    period: "Cover period",
    agent: "Referred by",
    renewalOf: "Renewal of",
  },
  noName: "Name not given yet",
  noVehicle: "No plate yet",

  detail: {
    documents: "Documents",
    answers: "Answers",
    messages: "Messages",
    quotes: "Quotes",
    nextStep: "Next step",
    noMessages: "No messages yet.",
    noQuotes: "No quotes yet.",
    fromClient: "Client",
    fromUs: "You",
    sampleFile: "Sample data — no file attached in the demo.",
    openFile: "Open file",
    waitingForClient: "Waiting for the client to upload this.",
    chosen: "Chosen by the client",
    payments: "Payment",
    noPayment: "No payment yet.",
    cover: "Cover",
    client: "Client",
    vehicle: "Vehicle",
    activity: "Messages sent",
    notFound: {
      title: "We can't find that application",
      body: "It may have been removed when the demo data was reset. Go back to the board.",
    },
  },

  // What the broker should do next, per stage. One primary action each.
  next: {
    check: {
      title: "Check the documents",
      body: "Compare each document with the answers, then mark it verified or ask for a new one.",
    },
    waitingDocs: {
      title: "Waiting for the client",
      body: "They still need to upload a document. You can nudge them on WhatsApp.",
    },
    draft: {
      title: "The client hasn't sent this yet",
      body: "They're still filling it in. If they've gone quiet, nudge them on WhatsApp.",
    },
    addQuotes: {
      title: "Send quotes",
      body: "We've prepared 3 quotes from the client's answers. Send them in one click, or add your own.",
    },
    quotesReady: {
      title: "Quotes added",
      body: "When you've added them all, mark quotes ready. The client can then choose.",
    },
    waitingChoice: {
      title: "Waiting for the client to choose",
      body: "They can see the quotes on their page. Nudge them if they need a push.",
    },
    awaitingPayment: {
      title: "Waiting for payment",
      body: "The client chose a cover and has an M-Pesa request. If they paid you another way, record it.",
    },
    issue: {
      title: "Paid — issue the cover",
      body: "Book the cover with the insurer, then enter the policy number. The client gets it on WhatsApp and email.",
    },
    issueDocs: {
      title: "Paid — check the documents first",
      body: "Verify every document, then issue the cover.",
    },
    covered: {
      title: "Done",
      body: "This client is covered.",
    },
  },

  actions: {
    sendQuotes: "Send 3 quotes",
    sendQuotesShort: "Send quotes",
    verifyAll: "Verify all documents",
    review: "Review",
    readReply: "Read reply",
    nudgeShort: "Nudge",
    addQuoteManually: "Add a quote by hand",
    nudge: "Nudge on WhatsApp",
    markVerified: "Mark verified",
    askReupload: "Ask for re-upload",
    addQuote: "Add quote",
    markQuotesReady: "Mark quotes ready",
    markCovered: "Mark covered",
    issueCover: "Issue cover",
    recordPayment: "Record a payment",
    open: "Open",
  },

  // Toasts match the button words (CLAUDE.md §7), and say messages are simulated.
  toasts: {
    quotesSent: "3 quotes sent — client notified (see Outbox)",
    nudged: "Sample client: the nudge is logged in the Outbox (sample numbers are never messaged).",
    nudgeOff: "Not sent: real WhatsApp is off on this site. Open the Outbox to see what's missing.",
    nudgeSent: "Nudge sent on WhatsApp",
    nudgeFailed: "WhatsApp not delivered — usually because that number hasn't joined the demo yet. See the Outbox.",
    verified: "Marked verified",
    verifiedAll: "All documents verified — client notified (see Outbox)",
    reuploadRequested: "Re-upload requested — client notified (see Outbox)",
    quoteAdded: "Quote added",
    quotesReady: "Quotes ready — client notified (see Outbox)",
    covered: "Cover issued — client notified",
    paymentRecorded: "Payment recorded — client notified",
    agentApproved: "Agent approved — welcome message sent",
    agentPaused: "Agent paused",
    agentResumed: "Agent active again",
    agentAdded: "Agent added",
    rateSaved: "Commission rate saved",
    agentPaid: (amount: string) => `${amount} paid — agent notified`,
    settingsSaved: "Automations saved",
    automationsRan: (count: number) =>
      count === 0 ? "Automations ran — nothing was due" : `Automations ran — ${count} ${count === 1 ? "message" : "messages"} sent`,
    renewalSent: "Renewal reminder sent",
  },

  errors: {
    generic: "That didn't work. Refresh the page and try again.",
    notAllowed: "That action doesn't fit this application's stage any more. Refresh to see the latest.",
    noQuotes: "Add at least one quote first.",
    verifyFirst: "Verify every document before issuing the cover.",
    signIn: "That password isn't right. Check it and try again.",
  },

  reupload: {
    title: (doc: string) => `Ask for a new ${doc}?`,
    description: "We'll message the client on WhatsApp with the reason you choose (simulated in the demo).",
    reasonLabel: "Reason",
    reasons: [
      { value: "blurry", label: "The photo is blurry", message: "The photo is blurry. Please take it again in good light." },
      { value: "cut_off", label: "Part of it is cut off", message: "Part of the document is cut off. Please make sure the whole page is in the photo." },
      { value: "wrong_document", label: "It's the wrong document", message: "This looks like a different document. Please upload the right one." },
      { value: "mismatch", label: "Details don't match", message: "Some details don't match your answers. Please check and upload it again." },
    ],
    confirm: "Send request",
    cancel: "Cancel",
    errors: { reason: "Choose a reason so the client knows what to fix." },
  },

  quoteForm: {
    title: "Add a quote",
    description: "Pre-filled with a suggestion. Check the numbers against the insurer's quote.",
    insurer: "Insurer",
    insurerHint: "Use the real insurer name once partners are confirmed.",
    coverType: "Type of cover",
    premium: "Premium per year",
    premiumForTrip: "Premium for this trip",
    excess: "Excess",
    benefits: "Benefits",
    benefitsHint: "Separate with commas, e.g. Windscreen cover, Towing",
    confirm: "Add quote",
    cancel: "Cancel",
    errors: {
      insurer: "Enter the insurer's name.",
      premium: "Enter the yearly premium in shillings.",
      excess: "Enter the excess in shillings, or leave it empty.",
      coverType: "Choose the type of cover.",
    },
  },

  whatsappCheck: {
    on: "Real WhatsApp is on (Twilio sandbox)",
    onBody: "Messages to applicants who joined the sandbox are really sent. Use the test to check your own number.",
    off: "WhatsApp is simulated on this site",
    offBody: (missing: string) =>
      `The server can't see: ${missing}. In Netlify, add them under Environment variables (scope: Functions or All), then Deploys → Trigger deploy.`,
    test: "Send test WhatsApp",
    testMessage: "Test from your Beacon Cover admin. If you can read this, real WhatsApp messages are working.",
    results: {
      sent: (status: string) => `Twilio accepted it (status: ${status}). Check your WhatsApp.`,
      not_configured: "Not sent: the Twilio keys aren't set on this site yet.",
      auth: "Not sent: Twilio rejected the keys. Check TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN (no spaces), then redeploy.",
      not_joined: "Not delivered: this number hasn't joined the sandbox. From WhatsApp, send your \"join …\" code to the sandbox number, then try again.",
      window:
        "Not delivered: WhatsApp only allows free-form messages within 24 hours of the person messaging you. From that phone, send any WhatsApp (e.g. \"hi\") to your Twilio WhatsApp number, then try again.",
      template_only:
        "Not sent: this WhatsApp number only accepts pre-approved templates. For the demo, use the Twilio Sandbox: set TWILIO_WHATSAPP_FROM to the sandbox number (usually whatsapp:+14155238886), send its \"join …\" code from your phone, then redeploy.",
      bad_sender: "Not sent: TWILIO_WHATSAPP_FROM isn't your sandbox number. Copy your WhatsApp sender from Twilio (e.g. whatsapp:+17372508034).",
      bad_number: "Not sent: Twilio says the destination number isn't valid for WhatsApp.",
      network: "Not sent: couldn't reach Twilio. Try again in a moment.",
      other: (detail: string) => `Not sent. Twilio says: ${detail}`,
    },
  },

  whatsapp: {
    realHint: "Opens your WhatsApp with the message typed. Press send.",
    autoHint: "Sends a real WhatsApp from the demo number.",
    sampleHint: "Sample client — the message is shown in the Outbox only.",
    sendFromOutbox: "Send on WhatsApp",
  },

  demo: {
    heading: "Demo tools",
    body: "Start the demo again from the sample applications. Only visible to you.",
    reset: "Reset demo data",
    confirmTitle: "Reset demo data?",
    confirmBody:
      "This removes every application, upload and message created during the demo, and brings back the sample applications. It can't be undone.",
    cancel: "Cancel",
    toast: "Demo data reset",
  },
  openApplication: "Open",

  today: {
    heading: (greeting: string) => greeting,
    greetings: { morning: "Good morning", afternoon: "Good afternoon", evening: "Good evening" },
    summary: (count: number) =>
      count === 0 ? "Nothing needs you right now." : count === 1 ? "1 thing needs you. Start at the top." : `${count} things need you. Start at the top.`,
    needsYou: "Needs you now",
    seeAll: "See all applications",
    allClear: "All clear. New applications, payments and replies will appear here the moment they happen.",
    ledgerHeading: "This month",
    ledger: {
      collected: "Premiums collected",
      collectedNote: (count: number) => `${count} ${count === 1 ? "payment" : "payments"} this month`,
      awaiting: "Waiting for payment",
      awaitingNote: (count: number) => `${count} ${count === 1 ? "client has" : "clients have"} chosen a cover`,
      commission: "Owed to agents",
      commissionNote: (count: number) => `${count} ${count === 1 ? "commission" : "commissions"} to pay`,
      renewals: "Renewals in 30 days",
      renewalsNote: "Reminders go out automatically",
    },
    pipelineHeading: "Pipeline",
    pipelineNote: "Every open application, by stage.",
    pipeline: {
      applying: "Applying",
      new: "To check",
      quotes: "Choosing a quote",
      payment: "Paying",
      issue: "To issue",
      covered: "Covered this month",
    },
    activityHeading: "Latest messages",
    activityAll: "See all messages",
    automationsOn: (count: number) => `${count} of 5 automations on`,
    automationsLink: "Manage automations",
  },

  payments: {
    heading: "Payments",
    intro: "Every M-Pesa payment, newest first. Payments are simulated in the demo.",
    totals: { collected: "Collected", pending: "Waiting", count: (n: number) => `${n} ${n === 1 ? "payment" : "payments"}` },
    columns: { client: "Client", amount: "Amount", receipt: "M-Pesa receipt", status: "Status", date: "Date" },
    status: { pending: "Waiting", paid: "Paid", failed: "Failed" },
    empty: { title: "No payments yet", body: "When a client pays for their cover, it appears here." },
  },

  recordPayment: {
    title: "Record a payment",
    description: "For clients who paid in cash, by bank or straight to the paybill. The client is told at once.",
    receipt: "Receipt or reference",
    receiptHint: "For example the M-Pesa code. Leave empty if there isn't one.",
    confirm: "Record payment",
    cancel: "Cancel",
  },

  issueForm: {
    title: "Issue the cover",
    description: "Enter the details from the insurer. The client gets them on WhatsApp and email, and renewal reminders are scheduled.",
    policyNumber: "Policy number",
    certificate: "Certificate number (optional)",
    certificateHint: "The digital motor certificate (DMVIC) number, if you have it.",
    startsOn: "Cover starts",
    confirm: "Issue cover",
    cancel: "Cancel",
    errors: {
      policyNumber: "Enter the policy number from the insurer.",
      startsOn: "Choose the date the cover starts.",
    },
  },

  renewals: {
    heading: "Renewals",
    intro: "Covers ending soon. Clients are reminded automatically 30, 14, 7 and 1 day before.",
    soon: "Ending in the next 30 days",
    later: "All active covers",
    columns: { client: "Client", cover: "Cover", ends: "Ends", left: "Left" },
    daysLeft: (n: number) => (n <= 0 ? "Today" : n === 1 ? "1 day" : `${n} days`),
    remind: "Send reminder now",
    empty: { title: "No covers ending soon", body: "Covers ending in the next 30 days appear here, with reminders already scheduled." },
    emptyAll: { title: "No active covers yet", body: "Issued covers appear here so you never miss a renewal." },
  },

  agents: {
    heading: "Agents",
    intro: "People who refer clients to you. Each gets a link; when a referred client pays, they earn commission.",
    requests: "Waiting for approval",
    active: "Agents",
    columns: { agent: "Agent", code: "Code", clients: "Clients", covered: "Covered", owed: "Owed", paid: "Paid" },
    approve: "Approve",
    pause: "Pause",
    resume: "Resume",
    pay: (amount: string) => `Pay ${amount}`,
    rate: "Commission %",
    saveRate: "Save",
    link: "Referral link",
    copyLink: "Copy link",
    copied: "Link copied",
    status: { pending: "Waiting", active: "Active", paused: "Paused" },
    stats: (clients: number, covered: number) => `${clients} ${clients === 1 ? "client" : "clients"} · ${covered} covered`,
    earned: (owed: string, paid: string) => `Owed ${owed} · paid ${paid}`,
    payNote: "Demo: no real M-Pesa payout is sent.",
    add: "Add an agent",
    addForm: {
      title: "Add an agent",
      description: "They can sign in at once with their phone number and start sharing their link.",
      name: "Full name",
      phone: "Phone number",
      email: "Email (optional)",
      code: "Referral code",
      codeHint: "Letters and numbers, for example JANE or JW25.",
      confirm: "Add agent",
      cancel: "Cancel",
    },
    empty: { title: "No agents yet", body: "Add an agent, or share the sign-up page: people who apply appear here for approval." },
    signupLink: "Agent sign-up page",
    errors: {
      rate: "Enter a commission between 0% and 20%.",
      nothingOwed: "Nothing is owed to this agent right now.",
      name: "Enter the agent's full name.",
      phone: "Enter a Kenyan mobile number.",
      code: "Use 3 to 12 letters or numbers.",
      codeTaken: "That code is already used. Choose another.",
      phoneTaken: "An agent with that number already exists.",
      email: "That email address doesn't look right.",
    },
  },

  automations: {
    heading: "Automations",
    intro: "Follow-ups that happen by themselves, so no client slips through. Every message appears in Messages.",
    rules: {
      autoQuote: { title: "Instant quotes", body: "Price every insurer the moment an application arrives, so the client can choose straight away." },
      nudgeStalled: { title: "Nudge clients who stop halfway", body: "WhatsApp and email after 1 hour, and again after a day, with a link back to where they stopped." },
      remindQuotes: { title: "Remind clients to choose a quote", body: "After 1 day, and again after 3 days." },
      remindPayment: { title: "Remind clients to pay", body: "After 2 hours, and again after a day, with the M-Pesa link." },
      renewalReminders: { title: "Renewal reminders", body: "30, 14, 7 and 1 day before cover ends, with a one-tap “Renew now” link. You get a daily list too." },
    },
    on: "On",
    off: "Off",
    save: "Save automations",
    runNow: "Run automations now",
    runNote: "They also run every hour by themselves, and whenever you open the admin.",
    commissionDefault: "Default commission for new agents (%)",
    channels: "Where messages go",
    whatsapp: "WhatsApp",
    email: "Email",
    channelOn: "Sending for real",
    channelOff: "Simulated — shown in Messages only",
    channelMissing: (names: string) => `To send for real, add ${names} to the site's environment variables.`,
    recent: "Recent runs",
    noRuns: "Nothing has run yet. Use “Run automations now” to try it.",
    ruleNames: {
      nudge_stalled: "Nudged",
      remind_quotes: "Quote reminder",
      remind_payment: "Payment reminder",
      renewal: "Renewal reminder",
      renewals_digest: "Renewals list sent to you",
    } as Record<string, string>,
  },

  login: {
    title: "Admin sign-in",
    description: "Enter the admin password to manage applications.",
    password: "Password",
    action: "Sign in",
  },

  outbox: {
    heading: "Outbox",
    intro: "Every message the system sent or would have sent. Only messages marked “Sent on WhatsApp” really went out; the rest are simulated.",
    empty: {
      title: "No messages yet",
      body: "When a client applies or you take an action, the message appears here.",
    },
    toClient: "To client",
    toAdmin: "To you",
    toAgent: "To agent",
    sentShort: "Sent",
    simulated: "Simulated",
    sent: "Sent on WhatsApp",
    failed: "Not delivered",
    failedHint: "Twilio didn't deliver it — usually because this number hasn't joined the WhatsApp demo yet.",
    viewApplication: "Open application",
  },
} as const;
