/** Agent portal strings (/agent). Agents refer clients and earn commission. */
export const agent = {
  title: "Agent portal",
  signOut: "Sign out",

  login: {
    title: "Agent sign-in",
    description: "Sign in with the phone number you registered as an agent.",
    phoneLabel: "Phone number",
    send: "Send code",
    codeLabel: "Code",
    codeHint: "Demo: no text message is sent. The code is always 123456.",
    confirm: "Confirm code",
    changeNumber: "Use a different number",
    noAccount: "Not an agent yet?",
    join: "Become an agent",
    errors: {
      phone: "Enter a Kenyan mobile number, for example 712 345 678.",
      unknown: "We don't have an agent with that number. Check it, or apply to become an agent.",
      code: "That code isn't right. Check it and try again.",
      expired: "That code has expired. Send a new one.",
    },
    sentToast: "Code sent (demo: no real text)",
  },

  join: {
    title: "Become an agent",
    description: "Refer people who need insurance. When they pay for their cover, you earn commission — paid to your M-Pesa.",
    how: ["Get your own link to share on WhatsApp.", "Your clients apply and pay online.", "You earn commission on every cover."],
    name: "Full name",
    phone: "Phone number",
    phoneHint: "You'll sign in with this number.",
    email: "Email (optional)",
    action: "Apply to be an agent",
    signIn: "Already an agent? Sign in",
    errors: {
      name: "Enter your full name.",
      phone: "Enter a Kenyan mobile number, for example 712 345 678.",
      email: "That email address doesn't look right. Check it, or leave it empty.",
      exists: "That number is already registered. Sign in instead.",
    },
    doneTitle: "Request sent",
    doneBody: "We'll review it and message you on WhatsApp when you're approved. Then sign in to get your link.",
    doneAction: "Go to sign-in",
  },

  dashboard: {
    greeting: (firstName: string) => `Hello, ${firstName}`,
    pendingTitle: "Waiting for approval",
    pendingBody: "We'll message you on WhatsApp when you're approved. Your link will appear here.",
    pausedTitle: "Your account is paused",
    pausedBody: "New clients from your link won't earn commission for now. Message us if you think this is a mistake.",
    linkHeading: "Your link",
    linkBody: (rate: string) => `Share it with anyone who needs insurance. You earn ${rate} of the premium when they pay.`,
    code: (code: string) => `Your code: ${code}`,
    share: "Share on WhatsApp",
    shareMessage: (link: string) =>
      `Need motor, health, travel or business insurance? Compare insurers and get covered from your phone in minutes:\n${link}`,
    copy: "Copy link",
    copied: "Link copied",
    stats: {
      clients: "Clients",
      covered: "Covered",
      owed: "Earned, not yet paid",
      paid: "Paid to you",
    },
    clientsHeading: "Your clients",
    clientsEmpty: "No clients yet. Share your link — clients who apply through it appear here.",
    commission: (amount: string) => `Commission ${amount}`,
    commissionPaid: "Paid",
    commissionOwed: "Owed",
    noCommissionYet: "Commission when they pay",
    applying: "Still applying",
    payoutsNote: "We pay commission to your M-Pesa. Demo: payouts are simulated.",
  },
} as const;
